### ISSUE TITLE
STL Files Issues

### ISSUE THREAD

**Issue by thepeel** [gary-peng/POD#1]
When I load the STL files into Cura they are all on end. I was able to rotate the divider and it worked well, however the top and bottom don't slice correctly. I've attached a screenshot of the first layer (with a skirt) as shown in OctoPrint.

<img width="1792" alt="Screen Shot 2019-08-21 at 11 06 54 PM" src="https://user-images.githubusercontent.com/984670/63485332-821b9780-c468-11e9-8648-41ecbb4224fd.png">

![Screenshot_2019-08-21 OctoPrint](https://user-images.githubusercontent.com/984670/63485150-e12cdc80-c467-11e9-9131-100c489b4011.png)

**Comment by phatbrain** [comment]
@gary-peng Please correct me if I am wrong but the issue being reported looks like @thepeel did not rotate the POD button (top and/or bottom). These are meant to be printed flat so you need to rotate them 90 degrees to the flat side as shown in my attached screenshot. I have printed several of these now in anticipation for receiving my package and they seem to go together fairly easily. I think the screw thread could be a bit larger so it is easier to screw them together but it does work with some effort. Also could be my 3D printer but I have printed one of each on all of my printers (Anycubic Mega-S, Prusa MK3S, BeeCreative B2X300, MP Delta, and Formlabs Form 2) and they all seem to fit together the same.

![Cura_POD](https://user-images.githubusercontent.com/23089247/64385331-dba0cc00-cffb-11e9-883d-299598847066.JPG)

**Comment by thepeel** [comment]
Yes rotating them works, I just don’t know why they’re not rotated by default. I usually have to mess with the file after rotating to get it to slice correctly. Otherwise it ends up with part below the z-axis. I was able to get one to print successfully, but it would have been nice not to have to rotate to print.

**Comment by gary-peng** [comment]
@thepeel Sorry for the late reply, I must've missed the notification in my inbox. @phatbrain you are correct, they are supposed to print as shown in your screenshot. The STL files should now be fixed
